version: '3'
services:
  pub:
    build:
      context: ./publisher
    # ports:
    #   - "3000:3000"
    depends_on:
      # - nats
      - nats-stream
  sub:
    build:
      context: ./subscriber
    # ports:
    #   - "3001:3000"
    depends_on:
      # - nats
      - pub
      - nats-stream
  nats:
    image: nats:2.0.4
  nats-stream:
    image: nats-streaming:0.16.2
    depends_on:
      - nats
