version: '3'
services:
  pub:
    build:
      context: ./publisher
    # ports:
    #   - "3000:3000"
    depends_on:
      - nats
  sub:
    build:
      context: ./subscriber
    # ports:
    #   - "3001:3000"
    depends_on:
      - nats
      - pub
  nats:
    image: nats:2.0.4
    expose:
      - "6222"
      - "4222"
